### ISSUE TITLE
ENM : Multiple errors after update (Symphony 2.5+)

### ISSUE THREAD

**Issue by twiro** [creativedutchmen/email_newsletter_manager#62]
The following update seems to have broken ENM somehow:

- Symphony 2.3.1 to Symphony 2.5.2 (with an inbetween-step at 2.3.6)
- ENM from 1.1 to 2.0.1

When trying to access the "Newsletter recipients"-page i get the following error:

`Symphony Fatal Error: Call to undefined method FieldCheckbox::buildDSRetrivalSQL()`
`An error occurred in .../extensions/email_newsletter_manager/lib/class.recipientsourcesection.php around line 195`

When trying to save an entry that includes the ENM-field I get another error:

`Symphony Fatal Error: Call to a member function get() on a non-object`
`An error occurred in .../extensions/email_newsletter_manager/fields/field.email_newsletter_manager.php around line 689`

Viewing the ENM-Senders or editing them works fine though.

**Comment by twiro** [comment]
The second error mentioned might be caused by **[this change](https://github.com/symphonycms/symphony-2/wiki/Migration-Guide-to-2.5-for-Developers#properties)** introduced in Symphony 2.5

**Comment by michael-e** [comment]
For the first problem, can you please go to line 195 of `/extensions/email_newsletter_manager/lib/class.recipientsourcesection.php` and replace the old typo'd name `buildDSRetrivalSQL` with `buildDSRetrievalSQL`? Does it help?

Regarding the second problem, I am rather sure that you are right. Please try:

```php
if (Symphony::Engine() instanceof Administration){
	if (is_callable(array('Symphony', 'Author'))) {
	    $author = Symphony::Author();
	} else {
	    $author = Administration::instance()->Author;
	}
	$author_id = $author->get('id');
}
```

Sorry for shooting in the dark, but I can't test this at the moment.

**Comment by twiro** [comment]
> For the first problem, can you please go to line 195 of /extensions/email_newsletter_manager/lib/class.recipientsourcesection.php and replace the old typo'd name buildDSRetrivalSQL with buildDSRetrievalSQL? Does it help?

It helps perfectly :)

> Regarding the second problem, I am rather sure that you are right. Please try...

That helps too! I now can save an entry containing an ENM-field, but then trying to actually send a Newsletter the next error appears - obviously caused by the same change than the previous error:

    Symphony Fatal Error: Call to a member function get() on a non-object
    An error occurred in.../extensions/email_newsletter_manager/lib/class.emailnewsletter.php around line 94

If I replace these 3 lines with the code you posted above I am finally able to succesfully send the Newsletter.

> Sorry for shooting in the dark, but I can't test this at the moment.

No worries - I'm quite thankful for your quick feedback and am in no way expecting final & well-tested fixes ;) And your proposal worked, so i don't really have any reason to complain!

**Comment by michael-e** [comment]
Dare to send a pull request (including a new release)? If not, no problem. I will just leave this open, so I can do it when I find the time. (I will need the extension working with Sym 2.6 rather soon anyway.)

**Comment by ShinShinman** [comment]
Hi. Have you managed to get ENM working with Symphony 2.6.1?
I applied all updates from this thread, plus one from [here](https://github.com/creativedutchmen/email_newsletter_manager/issues/65) but sending takes forever with no result (although I got only one recipient). When I cancel and hit Send button again I get an error:
```
Symphony Warning: strlen() expects parameter 1 to be string, object given
An error occurred in /home/shinman/domains/orkana39.pl/public_html/clients/alternativa/symphony/lib/toolkit/class.mysql.php around line 438
```
Refreshing resets whole thing. Again I can see Send button, but it takes no result. Have you got any ideas or solutions :) Thanks in advance!

Olaf

**Comment by michael-e** [comment]
I will work on this next week. Sorry for any delay, but I am really occupied.

**Comment by michael-e** [comment]
PS: By "next week" I actually mean "coming week" — I am German. :-)

**Comment by ShinShinman** [comment]
That is great! Thank you.

**Comment by ShinShinman** [comment]
Hi @michael-e.
Did you get a chance to work on it? Sorry for bothering you again.

**Comment by michael-e** [comment]
No, I am terribly sorry, but again the project priorities changed (based on client decisions), so I had to change my plans.

I won't make it this week either… I really hope that things get better soon.

**Comment by ShinShinman** [comment]
That's fine. I'll try to get this working anyway... Will let you know if I get lucky.

**Comment by michael-e** [comment]
@ShinShinman: Have you tested the current code from the development branch? I can' replicate your issue.

**Comment by ShinShinman** [comment]
Hi. Thank you for the update. Gonna try it tonight.

**Comment by michael-e** [comment]
Please try version 3.1. As far as I see, it is running smoothly.

I will close this "multiple errors" issue. If you experience any problems, please open new issues.
