### ISSUE TITLE
Symphony 2.6.1: Email Template Manager:  Recipient is empty, skipping.

### ISSUE THREAD

**Issue by wdebusschere** [creativedutchmen/email_newsletter_manager#65]
I have added a sections contacts and selected the section and corresponding fields correctly in newsletter recipients. Number of unique recipients is correct, but when i click preview, everything is under the name and under email adres nothing...

**Comment by michael-e** [comment]
Indeed ENM seems to be a bit broken on Symphony 2.6. If @creativedutchmen doesn't find the time, I will fix it in the coming weeks because I need it for a current project.

**Comment by creativedutchmen** [comment]
Hmm, that's a shame. I am currently completely unavailable until at least the 22nd of April. I might be able to find a bit of time somewhere afterwards though.

@michael-e how soon do you need it?

**Comment by michael-e** [comment]
Not before the end of April. I would be glad if you could help!

**Comment by creativedutchmen** [comment]
it will be a tight squeeze, but I'll try!

Please be sure to send a reminder, otherwise I will definitely forget about this.

**Comment by wdebusschere** [comment]
I don't think its too complicated to fix..
Is this html the normal output for the Email Newsletter Recipients›Group1 preview

<table>
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email Adress</th>
        <th scope="col">Valid</th>
      </tr>
    </thead>
    <tbody>
      <tr class="invalid">
        <td>
          <a href="http://www.site.com/symphony/publish/contacts/edit/141">Ana Rocha</a>
        </td>
        <td>hello@akibeo.com</td>
        <td>no</td>
      </tr>
      <tr class="invalid">
        <td>
          <a href="http://www.site.com/symphony/publish/contacts/edit/132">John Doe</a>
        </td>
        <td>info@e-xperience.be</td>
        <td>no</td>
      </tr>
    </tbody>
  </table>

**Comment by michael-e** [comment]
@wdebusschere: Unfortunately, at the moment I have no time to look into it.

@creativedutchmen: I hope that there won't be too many issues. :-) Reminder will be sent!

**Comment by wdebusschere** [comment]
Line 65 of file email_newsletter_manager/lib/class.recipientsourcesection.phpchanged to 
'valid' => @preg_match($validators['email'], $email)?true:false
'valid' => true // for testing
Output is correct, but in the log file when sending: 

Email Template Manager:  Recipient is empty, skipping.
09/04/2015 9:38 pm > UNKNOWN: Email Template Manager:  No valid recipients are selected, can not send emails.

**Comment by michael-e** [comment]
The preview issue whoch @wdebusschere described has been fixed by 477f25f1237ece4eec0e542b226253a8a368019a

I will test the original issue. I definitely want this extension to run smoothly on Symphony 2.6 by the end of the week.

**Comment by michael-e** [comment]
@wdebusschere: I can not replicate the issue with the current code from the development branch. Please re-open it if you still have problems.
