### ISSUE TITLE
Autoloader: Remove "require" Statements

### ISSUE THREAD

**Issue by michael-e** [creativedutchmen/email_newsletter_manager#67]
Symphony 2.6. uses an autoloader, so we should be able to clean up all the `require_once(TOOLKIT …` stuff. I found those statements in many files. It's not trivial, because we may have to add new/different stuff (especially for the background process), and everything must be tested properly.

Here's what I normally use for running background processes with Symphony 2.6:

```php
// Include autoloader:
require_once DOCROOT . '/vendor/autoload.php';

// Include the boot script:
require_once DOCROOT . '/symphony/lib/boot/bundle.php';

// Begin Symphony proper
ob_start();
symphony('administration');
// Drop useless session (if generated by Symphony)
$_SESSION = array();
cleanup_session_cookies();
ob_end_clean();
// Disable query logging (Re: memory issues, #2398)
Symphony::Database()->disableLogging();
```

**Comment by michael-e** [comment]
(This should be done after #66 has been pulled.)

**Comment by jonmifsud** [comment]
@michael-e I can probably clean it up and put it in #66 if you want. It's just the removal of all the other includes correct?

**Comment by michael-e** [comment]
You might try and remove all  `require_once(TOOLKIT …` lines except the ones in `cli.backgroundprocess.php` (which will be more complicated, see above). It would be interesting to see if everything still works if you remove the stuff.

**Comment by cremol** [comment]
@michael-e Did you get this extension working in 2.6.x?
I am using the development branch and set up everything like in the readme but when i click 'send' i get:  
![schermafbeelding 2015-12-13 om 14 17 57](https://cloud.githubusercontent.com/assets/804918/11767166/937208ce-a1a4-11e5-8ed9-b84adce2e9f0.png)  
I have a fresh 2.6.4 install, with only default extensions...

**Comment by michael-e** [comment]
Still working on it. I also need this.

**Comment by michael-e** [comment]
Can you please take a look in the extension's log file? Any relevant error there?

For me sending already works. So I assume that in the first place you have a problem with your template or newsletter setup, and then the background process doesn't find the `customError` method (which is a bug, of course).

**Comment by cremol** [comment]
Found some log files, i am on a shared host and it says 'shell_exec() has been disabled for security reasons'.  
So i guess there's nothing much i can do except for changing host...?

**Comment by michael-e** [comment]
Yep, without `shell_exec` you are lost.

**Comment by michael-e** [comment]
@cremol: I just pushed to development. It would be great if you could test the latest code, I hope that you will get a more useful error now.

**Comment by cremol** [comment]
Thanks, looking better now:

![schermafbeelding 2015-12-13 om 23 00 27](https://cloud.githubusercontent.com/assets/804918/11769697/88dca682-a1ed-11e5-98a8-1de0b8b48648.png)  

Seems like I've been running into this issue before:
http://www.getsymphony.com/discuss/thread/82064/3/#position-47  
  
You think a curl alternative could be implemented in the future? Or too much hassle?

**Comment by michael-e** [comment]
Oh great, I fixed the error message!

> You think a curl alternative could be implemented in the future?

Honestly, I won't find the time to do this. Also, I am not sure how `curl` could replace `shell_exec`, in other words: I am not sure if Huib was right in assuming that it would be a simple change.

I think that you should talk to your host. Completely disabling `shell_exec` is a bit like "we need this web-app to be super-safe, so we dropped the internet connection".

**Comment by cremol** [comment]
No problem, thats understandable.  
The host is planning on supporting this in the future but not very soon.  
Gonna talk to my client see if they wanna change host.  
Thanks anyway!
