### ISSUE TITLE
White page

### ISSUE THREAD

**Issue by Manaus** [creativedutchmen/email_newsletter_manager#68]
Hello,  
on installing the latest version (3.1?) on Sym2.6.1 I get a white page. Returning on the extensions list, email newsletter manager is pinned as non-installed.   
Thanks

**Comment by michael-e** [comment]
Sym 2.6.1? OMG. Can't you update to 2.6.3 at least? Much better!

That said, I have no idea about any breaking changes in 2.6.x. I will have to test with different Symphony versions.

**Comment by michael-e** [comment]
I have successfully installed ENM on Symphony 2.6.1.

Could it be that your workspace folder is not writable?

**Comment by Manaus** [comment]
Hello I cloned and tried to enable it on 2.6.2 and I am getting this error 

    Uncaught exception 'ErrorException' with message 'require_once
    (C:\Users\Me\wamp\www\Website/extensions/email_template_manager
    /lib/class.emailtemplatemanager.php): failed to open stream: 
    No such file or directory' in C:\Users\Me\wamp\www\Website\extensions
    \email_newsletter_manager\lib\class.emailnewsletter.php:8

Might be a slash issue?

**Comment by michael-e** [comment]
Hav you installed the Email **Template** Manager extension as well?

**Comment by Manaus** [comment]
Men.... #:X that was embarassing... 
Thanks!
